[package]
name = "sam-rs"
version = "0.1.0"

[dependencies]
ndarray = "0.15.6"
onnxruntime = { git = "https://github.com/karelnagel/onnxruntime-rs" }
opencv = "0.78.2"
tch = "0.11.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
